### ISSUE TITLE
The advancement screen is out of wack

### ISSUE THREAD

**Issue by ImpulsiveLass** [thedead2/customadvancements#9] opened 2023-10-14 16:43 UTC
I am in 1.20.1 forge with the 1.20.1-7.0.8 version of the mod
![2023-10-14_12 42 50](https://github.com/thedead2/customadvancements/assets/92990441/7253c9a3-82af-4983-9a44-3d46bd1a320c)
as you can see the bottom row of advancement tabs are translated to the right

**Comment by thedead2** [comment] 2023-10-15 16:52
Hi thanks for reaching out, which other mods have you installed? Maybe it's a bug between Custom Advancements and another mod. CA itself only alters the background of the advancement screen and which advancements are loaded. It shouldn't alter anything else.

**Comment by ImpulsiveLass** [comment] 2023-10-15 16:53
Well I'm working on a modpack and am using it as a tool for it,
![Screenshot 2023-10-15 125303](https://github.com/thedead2/customadvancements/assets/92990441/a4803410-98ec-4d4f-8d8f-337a4d458976)

**Comment by thedead2** [comment] 2023-10-15 20:36
If you remove Custom Advancements from your pack, does the advancement screen still looks broken or is it fixed?

**Comment by ImpulsiveLass** [comment] 2023-10-15 22:59
![2023-10-15_18 58 26](https://github.com/thedead2/customadvancements/assets/92990441/db94d298-5c51-4396-9c21-a5527c11973a)
Just removed custom advancements and opened up a world

**Comment by thedead2** [comment] 2023-10-16 07:15
Hmm, ok I will have a look at it and then get back to you.

**Comment by ImpulsiveLass** [comment] 2023-10-23 18:41
Could this be perhaps because I removed the sample advancements and that tab? Can’t test it rn, in lecture 

I also tested the mod in neoforge 47.1.76 and the issue persisted

**Comment by thedead2** [comment] 2023-10-23 19:22
No that's probably not the reason. The example tab is just that, an example. You could basically have the mod installed and no advancement loaded, wouldn't really make sense but it's possible.
I'm quite certain that it's an incompatibility between CA and another mod. Hadn't time testing it though but I will look at it tomorrow.
If you want to, you could also try removing one mod after another without removing Custom Advancements and test whether the bug persists.

If I'm not mistaken currently all forge mods are compatible with NeoForge as they share most of their code. But the mod wasn't programmed for NeoForge so if something isn't working in NeoForge there's currently no fix. But I will consider releasing a version for NeoForge if the time has come.

**Comment by thedead2** [comment] 2023-10-24 13:09
Ok I tried to recreate your mod pack it makes no sense with the list you've provided above. There are lots of mods that are for fabric which will definitely not work with forge, also a lot of mods are outdated so make sure to have the newest versions of these mods installed.
It would be helpful if you could provide a link to download your mod pack so I don't have to recreate it mod per mod.

**Comment by ImpulsiveLass** [comment] 2023-10-26 21:25
oh I don't have the pack anymore, I've been changing it actively

**Comment by thedead2** [comment] 2023-10-27 04:04
Ok does the issue still persist with the new version of the pack? If so, could you please provide a link to the new pack.

**Comment by ImpulsiveLass** [comment] 2023-11-02 16:33
I don't currently use the mod since I realized I can remove advancements by going into the jars and deleting the relevant json

**Comment by thedead2** [comment] 2023-11-02 18:59
Please note: If you are altering the jars of mods you have downloaded, this firstly might not be compliant with the license of the mod, secondly you will habe to delete the json files manually with every update of any mod and thirdly you can not really share the modpack via clients like the curseforge client as those always download the mods directly.
Anyway, this is off-topic.
As you don't use the mod currently and I can't reproduce the bug with the given information I'm closing this issue now. Feel free to reopen it if the bug occurs again.

**Closed as not planned by thedead2** 2023-11-02 18:59 UTC
Labels: wontfix
